Repository paketo-buildpacks/bellsoft-liberica, pull requests merged in 2021-08, with the labels that each got.

#113 Allow Tiny stack
  buildpack.toml
Labels: semver:minor, type:enhancement

#117 Update libjvm to 1.28.0 to support BP_JVM_TYPE variable
  README.md
  buildpack.toml
  go.mod
  go.sum
Labels: semver:patch, type:dependency-upgrade

#123 Change the order of buildplan candidates such that it goes from most specific to least specific
  liberica/detect.go
  liberica/detect_test.go
Labels: semver:patch, type:bug
