Repository paketo-buildpacks/bellsoft-liberica, pull requests merged in 2021-09, with the labels that each got.

#124 Fixes bug where JRE was being installed into the launch container for native-image apps
  liberica/build.go
  liberica/build_test.go
Labels: semver:patch, type:bug

#126 Update libpak to 1.53.0 & libjvm to 1.30.0
  go.mod
  go.sum
Labels: semver:minor, type:dependency-upgrade

#128 Add Java 17
  .github/pipeline-descriptor.yml
  buildpack.toml
Labels: semver:minor, type:dependency-upgrade

#130 Added Java NMT, Debug & JMX Helpers
  README.md
  buildpack.toml
  go.mod
  go.sum
  liberica/build.go
  liberica/build_test.go
Labels: semver:minor, type:enhancement

#133 Clean up after dependabot
  go.sum
Labels: semver:patch, type:dependency-upgrade
