Repository paketo-buildpacks/bellsoft-liberica, pull requests merged in 2021-11, with the labels that each got.

#166 Fixes dependencies
  go.sum
Labels: type:task, semver:patch

#171 Fixed go.sum issue for Gomega 1.17 bump
  go.sum
Labels: semver:patch, type:dependency-upgrade

#174 Add CPE & PURL info to buildpack.toml & bump libcnb to 1.25.0
  buildpack.toml
  cmd/main/main.go
  go.mod
  go.sum
  liberica/build_test.go
Labels: semver:patch, type:dependency-upgrade

#185 Fix for not adding empty BOM entries under 0.7
  go.mod
  go.sum
  liberica/build.go
  liberica/build_test.go
Labels: semver:patch, type:bug
