Repository paketo-buildpacks/bellsoft-liberica, pull requests merged in 2022-02, with the labels that each got.

#210 Generate label-based BOM for all API versions
  go.mod
  go.sum
  liberica/build.go
  liberica/build_test.go
Labels: semver:minor, type:enhancement

#220 Updated PURL pattern to match NIK version instead of Java version
  .github/pipeline-descriptor.yml
  .github/workflows/update-native-image-11.yml
  .github/workflows/update-native-image-17.yml
Labels: semver:patch, type:bug

#223 Go 17 and module versioning
  cmd/main/main.go
  go.mod
  go.sum
  liberica/build_test.go
  liberica/detect_test.go
  scripts/build.sh
Labels: semver:minor, type:dependency-upgrade
